baseURL = "https://mostlygeek.com"
languageCode = "en-us"
title = "mostlygeek"

[taxonomies]
  tag = "tags"

[permalinks]
  blog = "/:filename/"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.main]]
    name = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "benson"
    url = "/pages/about/"
    weight = 2
  [[menu.main]]
    name = "articles"
    url = "/article/"
    weight = 3
# uncomment to create a tags page
#  [[menu.main]]
#    name = "Tags"
#    url = "/tags/"
#    weight = 3

[params]
  dateFormat = "Jan 2, 2006"
